# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now_add=True)),
                ('reisekurzel', models.CharField(max_length=20, verbose_name='Kürzel')),
                ('reisename', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(max_length=1000)),
                ('link', models.CharField(max_length=500)),
                ('dauer', models.IntegerField()),
                ('reiseheader', models.ImageField(default='media/China_mit_Yangtze.jpg', upload_to='', verbose_name='Titelbild der Reise')),
            ],
            options={
                'verbose_name_plural': 'Reisen',
            },
        ),
        migrations.CreateModel(
            name='Reiseleiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Reiseleiter',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now_add=True)),
                ('reisetag', models.IntegerField()),
                ('foto', models.ImageField(upload_to='')),
                ('beschreibung', models.TextField(max_length=1000)),
                ('reise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reiseberichte.Reise')),
            ],
            options={
                'verbose_name_plural': 'Tage',
            },
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now_add=True)),
                ('reisebeginn', models.DateField()),
                ('reiseende', models.DateField(editable=False)),
                ('favorite', models.BooleanField(default=False, editable=False)),
                ('reiseleiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reiseberichte.Reiseleiter')),
                ('reisename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reise', to='reiseberichte.Reise')),
            ],
            options={
                'verbose_name_plural': 'Termine',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='reisedatum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termine', to='reiseberichte.Termin'),
        ),
    ]
